# disabled due to large image size
name: Build and Push ai-lab Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          context: ./docker
          file: docker/tf-2.16.1-cuda-12.dockerfile
          labels: |
            cuda=12
            tf=2.16.1
            jax=cuda12_local
